# Site Info
title:              "성병모의 피땀눈물"
description:        "성병모를 스쳐지나간 프로그래밍 피땀눈물 그리고 쓰잘데기없는 작은 지식"
author_name:        "byeoom" # change this to your name
logo_url:           https://avatars2.githubusercontent.com/u/75523696?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://byeoom.github.io # https://heiswayi.github.io main url, http://127.0.0.1:4000 local
baseurl:             #/the-plain
permalink:          /:title # Post permalink
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
